import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import logo from 'public/logo.gif'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'eKaštela',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="hr">
      
      <body className={inter.className}>
        <header>
          <img src={logo.src} alt="Logo" className="mr-2" />
          <nav className="flex space-x-16 mx-2">
            <Link href="/" className='hover:text-emerald-700'>Početna</Link>
            <Link href="/about" className='hover:text-emerald-700'>O nama</Link>
            <Link href="/forum" className='hover:text-emerald-700'>Građanski forum</Link>
            <Link href="/login" className='hover:text-emerald-700'>Prijava</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
